title: Fluidd
description: >-
  Fluidd is the Klipper UI. Focused on usability, flexibility and a responsive experience.
logo: /assets/images/fluidd_icon.svg
tagline: Fluidd, the Klipper UI.

# Build settings
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://docs.fluidd.xyz" # the base hostname & protocol for your site, e.g. http://example.com
# permalink: pretty
exclude: ["node_modules/", "*.gemspec", "*.gem", "Gemfile", "Gemfile.lock", "package.json", "package-lock.json",  "script/", "LICENSE.txt", "lib/", "bin/", "README.md", "Rakefile"
, "docs/tests/"
]
remote_theme: pmarsceill/just-the-docs
color_scheme: "fluidd"
search_enabled: true

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/cadriel/fluidd" # the github URL for your repo
gh_edit_branch: "develop" # the branch that your docs is served from
gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "edit" # "tree" or "edit" if you want the user to jump into the editor immediately

# Use front matter defaults to set og:image
# https://jekyllrb.com/docs/configuration/front-matter-defaults/
defaults:
  -
    scope:
      path: ""
    values:
      image: assets/images/ogfluidd.png
